### ISSUE TITLE
R-T5.1-6: Support of FaaS deployment to OpenFaas

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#10]
ID: | R-T5.1-6
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy TOSCA blueprint to OpenFaas
Requirement: | Support of FaaS deployment to OpenFaas
Extended   Description: | The TOSCA bluprints and Ansible playbooks   should be developed to deploy RADON model on OpenFaaS
Priority: | Must have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Test if such playbooks and blueprints are   available in Template Library repository and its possible to deploy toy   example to OpenFaas platform only using playbooks and blueprints from   Template Library.

**Comment by anzoman** [comment]
Well it is your lucky day since this is possible and has been provided within this repository: https://github.com/radon-h2020/demo-tosca-blueprint-openfaas where we prepared a blueprint of TOSCA image-resize/thumbnail-genrator application that can be deployed with xOpera and features MinIO object storage and OpenFaaS. There is even a part where you can set up those two tools with xOpera so that you don't have to prepare them before. So, I think that if you agree this issue can be marked as done and closed.

**Comment by anzoman** [comment]
I forgot to mention that the templates for OpenFaaS are also available in Template Library:

![image](https://user-images.githubusercontent.com/41727816/84392294-72895d00-abfa-11ea-887e-6427d3b2c5ff.png)

**Comment by cankarm** [comment]
That's perfect. From now we will close this issue and missing things add as new issues.

**Comment by gcasale** [comment]
Closed state approved.
